source 'https://rubygems.org'

# group :jekyll_plugins do
#   gem 'github-pages'
# end


gem 'jekyll',	'3.0.3'
gem 'github-pages-health-check',	'1.1.0'
gem 'github-pages',	'66'
gem 'html-pipeline',	'2.3.0'
gem 'jekyll-coffeescript',	'1.0.1'
gem 'jekyll-feed',	'0.4.0'
gem 'jekyll-gist',	'1.4.0'
gem 'jekyll-github-metadata',	'1.9.0'
gem 'jekyll-mentions',	'1.1.2'
gem 'jekyll-paginate',	'1.1.0'
gem 'jekyll-redirect-from',	'0.10.0'
gem 'jekyll-sass-converter',	'1.3.0'
gem 'jekyll-seo-tag',	'1.3.2'
gem 'jekyll-sitemap',	'0.10.0'
gem 'jekyll-textile-converter',	'0.1.0'
gem 'jemoji',	'0.6.2'
gem 'kramdown',	'1.10.0'
gem 'liquid',	'3.0.6'
gem 'rdiscount',	'2.1.8'
gem 'redcarpet',	'3.3.3'
gem 'RedCloth',	'4.2.9'
gem 'rouge',	'1.10.1'
# gem 'ruby'	2.1.7
gem 'safe_yaml',	'1.0.4'
gem 'sass',	'3.4.21'



# gem 'jekyll', '3.0.2'
# gem 'jekyll-sass-converter', '1.3.0'
# gem 'jekyll-textile-converter', '0.1.0'
# gem 'kramdown', '1.9.0'
# gem 'rdiscount', '2.1.8'
# gem 'redcarpet', '3.3.3'
# gem 'RedCloth', '4.2.9'
# gem 'liquid', '3.0.6'
# gem 'rouge', '1.10.1'
# gem 'jemoji', '0.5.1'
# gem 'jekyll-mentions', '1.0.0'
# gem 'jekyll-redirect-from', '0.9.1'
# gem 'jekyll-sitemap', '0.9.0'
# gem 'jekyll-feed', '0.3.1'
# gem 'jekyll-gist', '1.4.0'
# gem 'jekyll-paginate', '1.1.0'
# gem 'github-pages-health-check', '0.6.0'
# gem 'jekyll-coffeescript', '1.0.1'
# gem 'jekyll-seo-tag', '0.1.4'
# gem 'github-pages', '44'
# gem 'html-pipeline', '2.3.0'
# gem 'sass', '3.4.21'
# gem 'safe_yaml', '1.0.4'
# gem 'maruku', '0.7.0'
# gem 'pygments.rb', '0.6.3'
# gem 'jekyll-img-converter', '0.1.0'